server:
  port: 8761
spring:
  application:
    name: service-registry
eureka:
  instance:
    hostname: "${HOSTNAME:localhost}.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://127.0.0.1:8761/eureka}